import img from "../../images/SkyDive.webp";
import ui from "../../images/ui.webp"
import code from "../../images/code.webp"
import sky from "../../images/sky.webp"
import frames from "../../images/frames.webp"
import cad from "../../images/cad.webp"
import sumo from "../../images/sumo.webp"
import reel from "../../images/reels.webp"
import goal from "../../images/goal.webp"
import eclash from "../../images/eclash.webp"
import Lift from "../../images/Lift.webp"
import line from "../../images/line.webp"
import momentum from "../../images/momentum.webp"
import terraglide from "../../images/terraglide.webp"
import firepower from "../../images/firepower.webp"
// export const eventData = [
//   {
//     type: "Technical",
//     name: "UI BATTLES",
//     day: "1",
//    fee:100,
//     time: "1:30 PM",
//     venue: "APTI LAB OR DEPARTMENT LAB",
//     date: "8th Dec",
//     maxlimit: 2,
//     mode: "online",
//     image: img,
//     prize: "₹10,000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ 400 per team",
//     ],
//     teamReq: [
//       "Each team should consist of a maximum of 2 members.",
//       "Solo participation is also allowed.",
//       "Team members must be of the same school or college.",
//       "Participants should get their school/college ID card.",
//       "Any number of teams from a school/college is allowed.",
//     ],
//     desc: "Hello coders! Are you ready for an exciting challenge that aligns with your passion for web development. Welcome to the Web Dev code the logic & Page Cloning Challenge, where your fundamental coding skills will be put to the ultimate test.",
//     smallDesc: "Participants shall be competing ",
//     format: {
//       "Round-1  CODE THE LOGIC :": [
//         "Teams will be given a set of HTML snippets. Each snippet will have an associated description indicating the task that needs to be performed. Participants have to choose the correct javascript code to satisfy the functionality demanded.(MCQ type).There will be only one correct option",
//         "There will be no elimination in this round",
//         "Teams will be scored on the number of correct options they select",
//         " If 2 teams get the same score, then the team which submitted first will be given higher priority.(only in case there is a tie after the second round)",
//         "This score will be carried forward for the next round",
//         "It will carry only 30% of weightage",
//       ],
//       "Round-2 - PAGE CLONING CHALLENGE :": [
//         "Teams will be provided with a figma design which they have to clone using HTML, CSS and javascript only..",
//         " Teams have to clone the figma design in the specified duration",
//         "Teams will be evaluated based on how closely their web page aligns with the provided figma design",
//         "Participants will be provided with internet to refer only in this round",
//         "It will carry 70% of weightage",
//       ],
//     },
//     rules: [
//       "Usage of cell phones or any other electronic devices is prohibited. ",
//       "Communication with any other team during the event is prohibited, both in online and offline mode.",
//       "The Organizer's decision will be final.",
//       "These rules are subjected to change.",
//     ],
//     judgingCriteria: [
//       "The team with the maximum total score from both the rounds will be declared the winner. i.e, after adding the score from the first round and the second round whichever team has higher score that team will be declared the winner",
//     ],
//     contactDetails: [
//       {
//         name: "Babith",
//         phoneNumber: "+91 8971206807",
//       },
//     ],
//     link: " ",
//   },

//   {
//     type: "Technical",
//     name: "LINE FOLLOWER",
//     day: "1",
//     fee:200,
//     time: "1:30 PM",
//     venue: "2nd Floor Seminar Hall",
//     date: "8th Dec",
//     maxlimit: 5,
//     mode: "online",
//     image: img,
//     prize: "₹10000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ 400 per team",
//     ],
//     teamReq: [
//       "All the team members must be full-time students at an accredited University/College/School.",
//       "There are no restrictions on the number of teams from the same Institute.",
//       "The team should contain 3-5 members in total.",
//     ],
//     desc: "A competition played by one or two teams at a time, with each team consisting of one wireless bot. The objective is to build a bot capable of completing various challenges along the way in the shortest period of time. The competition will test the robot's speed, accuracy, and ability to handle complex track layouts including intersections, curves, and junctions",

//     smallDesc:
//       "Winners of the competition will be awarded prizes worth  ₹10,000/-.",
//     format: {
//       "Round-info": [
//         "The competition will consist of 3 rounds.",
//         "Each round will have a different map which will be disclosed on the day of the event.",
//         "Round-specific rules will be explained just before the start of that particular round.",
//         "All the rounds will have a black line/trajectory on a white arena.",
//       ],
//     },
//     rules: [
//       "Two or more teams cannot share one robot; moreover, the robot cannot be ready-made.",
//       "A practice arena will be provided, but no test/practice on the main arena will be allowed.",
//       "Once a robot has crossed the start line, it must remain fully autonomous.",
//       "The width of the trajectory of the arena is approximately 3 cm.",
//       "Participants should arrange their own batteries, and the power supply must be on board.",
//       "The robot must remain intact until results are announced.",
//       "The judges' verdict is considered final, and no arguments will be entertained.",
//     ],
//     judgingCriteria: [
//       "Score = (Time taken to reach the finish line)+(penalty)",
//     ],
//     contactDetails: [
//       {
//         name: "AKSHAY SHET",
//         phoneNumber: "+91 9449384765",
//       },
//     ],
//     link: " ",
//   },
//   {
//     type: "Technical",
//     name: "CAD EVENT",
//     day: "1",
//     fee:300,
//     time: "1:30 PM",
//     venue: "CAD LAB(Mechanical Department)",
//     date: "8th Dec",
//     maxlimit: 3,
//     mode: "online",
//     image: img,
//     prize: "₹5000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ XXXX per team",
//     ],
//     teamReq: [
//       "All the team members must be full-time students at an accredited University/College/School.",
//       "Students from multiple Colleges can form a team.",
//       "There are no restrictions on the number of teams from the same Institute.",
//       "The team should have 2-3 members in total.",
//       "Each participant may only be a part of one team.",
//     ],
//     desc: "The competition involves creating a replica of a CAD model which is enclosed within a cube provided to the contestants. The model given will only have TWO dimensions at the beginning of the event. The other dimensions will be provided after a specific interval of time, one by one. The rest of the dimensions must be self-estimated.  The team with the closest resembling CAD model to the reference model wins. ",
//     smallDesc:
//       "Winners of the competition will be awarded prizes worth ₹5000/-.",
//     format: {
//       "Round-info": [
//         "The CAD Model enclosed in a cube will be presented on the screen.",
//         "A copy of the model having a top, front, and isometric view with no dimensions will be given in hardcopy to each team.",
//         "The Model on the screen will have only 2 dimensions for the beginning.",
//         "The other dimension will be provided with a time gap of 1 hour or 30 mins, depending on the importance of the dimension.",
//         "Only 75% of the dimensions are provided until the end of the event.",
//         "Material specifications will be given at the last hour of the competition.",
//         "Contestants can make the model on the given PC or on their own laptop.",
//       ],
//     },
//     rules: [
//       "Each team is given one PC with Solidworks/Fusion360.",
//       "The organizing team holds all the authority to disqualify the team without warning and without stating the reason. This decision is final and binding on the participants.",
//       "Having their own laptop is compulsory as no more than one PC is provided.",
//       "The event has a duration of 4 hours, and contestants are allowed a 30-minute break 2 hours from the start.",
//       "The Scoring Criteria - Total points that can be awarded:  10 distributions-4 points for getting the weight of the model, 4 points for the correct dimension ,2 points for rendering of the model",
//     ],
//     judgingCriteria: [
//       "The team should not try to copy the dimensions from the other teams.",
//       "Any team found practicing malpractice by sharing information with other teams or trying to copy the dimensions will be disqualified.",
//       "The organizing team retains the authority to disqualify a team without prior notice or the need to provide a specific explanation.",
//     ],
//     contactDetails: [
//       {
//         name: "ROHAN BALAMKAR",
//         phoneNumber: "+91 8618983737 ",
//       },
//     ],
//     link: " ",
//   },
//   {
//     type: "Technical",
//     name: "CODE QUEST",
//     day: "2",
//     fee:400,
//     time: "9:30 AM",
//     venue: "Apti lab or Department lab",
//     date: "9th Dec",
//     maxlimit: 3,
//     mode: "online",
//     image: img,
//     prize: "₹10000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ XXXX per team",
//     ],
//     teamReq: [
//       "All the team members must be full-time students at an accredited University/College/School.",
//       "Students from multiple Colleges can form a team.",
//       "There are no restrictions on the number of teams from the same Institute.",
//       "The team should have 2-3 members in total.",
//       "Each participant may only be a part of one team.",
//       "Participants should get their school/college ID card.",
//     ],
//     desc: "Want to show off your coding skills? Then you have come to the right place. Here you can show your skills by completing the given challenges. Face against your peers to test your current level. Make sure to keep your foundations of coding skills strong. ",
//     smallDesc:
//       "Winners of the competition will be awarded prizes worth ₹10000/-.",
//     format: {
//       "Round-1  THE PRELIMINARY TEST :": [
//         "Teams will be given a set of MCQs that are based on programming questions where they might have to find the output and other basic coding questions. They must answer within a given time duration.",
//         "Top xx teams with the highest score will be selected to the next round.",
//         "In case of tie, the group who submitted first will have the priority.",
//         "Communicating with other teams will not be allowed.",
//       ],
//       "Round-2 :": [
//         "A group of codes will be shared to all the teams (5-10 questions).The participants will have to find the total number errors in the given code and write the line number in which the error is present. Points will be allocated to the teams based on the number of errors they find. Teams will have to complete the event within the given time limit.",
//       ],
//       "Round-3 :": [
//         "A group of the questions will be given to the contestants. Participants will have to write the code for the given problems. Teams will have to write the code by keeping the given constraints or conditions to them. The participants will have to use python language to write the code.  Points will be given based on the number of problems solved. Teams will have to complete the event within the given time limit.",
//       ],
//     },
//     rules: [
//       "Communication with other teams is not allowed during the event.",
//       "No external electronic device is allowed to be used during the event.",
//       "The Organizer's decision will be final.",
//       "In case of foul play the team will be disqualified.",
//     ],
//     judgingCriteria: [
//       "Winner will be decided by the number of points each team has earned.",
//       "In case of two teams having the same points, a tie-breaking round will be conducted, where teams will be given 5-Questions, whichever team completes it fast with most correct answers will be considered.",
//     ],
//     contactDetails: [
//       {
//         name: "ANUDEEP K K",
//         phoneNumber: "+91 8762339086 ",
//       },
//       {
//         name: "BHAT NISHANTH GANESH",
//         phoneNumber: "+91 8073372867 ",
//       },
//     ],
//     link: " ",
//   },
//   {
//     type: "Technical",
//     name: "TUB OF BOTS",
//     day: "2",
//     fee:500,
//     time: "9 AM",
//     venue: "Badminton Court(main block)",
//     date: "9th Dec",
//     maxlimit: 4,
//     mode: "online",
//     image: img,
//     prize: "₹5000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ 400 per team",
//     ],
//     teamReq: [
//       "All the team members must be full-time students at an accredited University/College/School.",
//       "Students from multiple Colleges can form a team.",
//       "There are no restrictions on the number of teams from the same Institute.",
//       "The team should have 3-4 members in total.",
//       "Participants should get their school/college ID card.",
//     ],
//     desc: "Two bots from different teams will compete against each other in a certain arena to pull the opposition team to their side. As soon as the red mark on the rope crosses the median line, the team to pulls the rope to their area wins the game.  ",
//     smallDesc:
//       "Winners of the competition will be awarded prizes worth ₹5000/-.",
//     format: {
//       "Round-info": [
//         "There will be three sessions: PRELIMINARY, SEMIFINAL, and FINAL.",
//         "The winners of each session will advance to the next.",
//         "The opposition team will be chosen by drawing lots.",
//         "If an odd number of bots are present, then one bot will directly go to the next round (only in the PRELIMINARY).",
//         "Each session will comprise two rounds.",
//         "Who wins the toss will choose the side of the arena.",
//         "The position of the two competitors' bots will be interchanged after one round.",
//         "The team that pulls the other bot over the line will advance into the next session.",
//         "The bot can only be controlled by one person on the team. For the next round, the controlling person can be changed.",
//         "Any of the parts of the Bot cannot be shared with other Teams.",
//         "Competitors should bring the charger for the battery.",
//         "The dimensions of the arena will be 4*3 feet. (Arena might change according to the requirement)",
//       ],
//     },
//     rules: [
//       "The weight of the robot should not exceed the limit of 5 kg.",
//       "The dimensions of the bot should not exceed the limit: width: 30cm, length: 30cm, height: 30cm.",
//       "A pardon of tolerance in the amount of 10% will be given in the case of the dimensions and weight.",
//       "Any discrepancy in the dimensions will lead to the team's disqualification.",
//       "The bot cannot be made using ready-to-assemble kits.",
//       "The bot must contain a structure similar to a hook for securing the rope.",
//     ],
//     judgingCriteria: [
//       "The judges' verdict should be considered final and no arguments will be entertained.",
//     ],
//     contactDetails: [
//       {
//         name: "BHAVISH RAI B",
//         phoneNumber: "+91 9591002456 ",
//       },
//     ],
//     link: " ",
//   },
//   {
//     type: "Technical",
//     name: "WATER ROCKET",
//     day: "2",
//     fee:600,
//     time: "9 AM",
//     venue: "GROUND BESIDE BACK CRICKET GROUND",
//     date: "9th Dec",
//     maxlimit: 4,
//     mode: "online",
//     image: img,
//     prize: "₹5000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ 400 per team",
//     ],
//     teamReq: [
//       "Team should not exceed more than 4 people.",
//       "Team members should be from the same institution.",
//       "Each participant may only be a part of one team.",
//       "Any number of teams from a school/college is allowed.",
//     ],
//     desc: "How exhilarating will it be to build and fly your own rocket? Get ready to launch into a world where innovation takes flight, and engineering prowess meets the power of H2O! Join us as we witness rockets of all shapes and sizes, each meticulously crafted to soar to the sky, powered only by the might of water and the brilliance of engineering minds. Welcome to the most exhilarating event of the year, where creativity soars higher than ever before, Splash & Dash - Aerophilia23's Water Rocket Competition! ",
//     smallDesc:
//       "Winners of the competition will be awarded prizes worth ₹5000/-.",
//     format: {
//       task: [
//         "Teams are required to construct a water propelled rocket pressurized with air using bottles. These will be then tested for their efficiency and working against each other.",
//       ],
//       specifications: [
//         "The total capacity of the rocket shouldn't exceed 2.5 liters.",
//         "Boosters and staging of the rocket are allowed.",
//         "Total capacity of the booster and stage should not exceed 1 liter. If boosters and stage are included, the total capacity of the rocket shouldn’t exceed 3.5 liters.",
//       ],
//       "Round-1  How Far?:": [
//         "In this round, teams must launch the rockets and try to obtain the maximum score.",
//         "Teams will get 10 points for each 10 meters of the rocket's horizontal flight distance",
//         "Rockets which don't go further than 20 meters will not fetch any points",
//         "Rockets which go more than 100 meters will get 20 points for consecutive 10 meters.",
//       ],
//       "Round-2 - Hit the target :": [
//         "In this round, the rocket launched should hit an area marked at a distance of 65m.",
//         "The target area will be in circular shape with three regions.",
//         "Innermost region of diameter 10 meters (30 points)",
//         "Middle region of diameter 15 meters (20 points)",
//         " Outermost region of diameter 20 meters (10 points)",
//         "Rockets that do not touch the target will receive a negative score of 20 points.",
//       ],
//     },
//     rules: [
//       "Teams from the same school are not allowed to exchange their equipment or help the other team.",
//       "Launching angle to be decided by the participating team.",
//       "Usage of Electronic systems, Fireworks, Explosives, or parachutes is restricted.",
//       "Working fluid is water and only it should be used in the propulsion of the rocket; no other things or systems should be used.",
//       "Boosters and staging are allowed.",
//       "Ground inspection will be done.",
//       "Teams will get 2 tries in each round.",
//       "Range (in meters) and time of flight (in seconds) will be measured by the organizers.",
//       "Only members of the participating team will be allowed to launch.",
//     ],
//     judgingCriteria: [
//       "All decisions about scoring, gameplay, and timing made by the coordinators and judges are final.",
//       "All the decisions taken by the judges or the volunteers will be considered and no argument will be allowed.",
//       "Any changes in the rules will be mentioned on the website.",
//       "Teams failing to abide by the rules will lead to disqualification.",
//     ],
//     contactDetails: [
//       {
//         name: "Tejashvi",
//         phoneNumber: "+91 8296584492 ",
//       },
//     ],
//     link: " ",
//   },
//   {
//     type: "Technical",
//     name: "TERRAGLIDE",
//     day: "1",
//     fee:800,
//     time: "6:30 pm",
//     venue: "Netravati Auditorium",
//     date: "11th Nov",
//     maxlimit: 10,
//     mode: "online",
//     image: img,
//     prize: "₹25000",
//     registrations: [
//       "A maximum of only 64 teams can participate in each event. So register fast.",
//       "Registrations will start from 11 th Oct 9:00am IST and will end on 2 rd Nov 7:00pm IST.",
//       "VALORANT Registration Fees 750/- per team (150/- per head).",
//       "CODM Registration Fees 500/- per team (100/- per head).",
//       "Each team will be given a Unique team code after the registration and payment is done.",
//     ],
//     teamReq: [
//       "There are no specific requirements for the team or the team members.",
//     ],
//     desc: "Welcome to the exhilarating event of Aerophilia'23 TerraGlide, an event that pushes the boundaries of engineering creativity and precision. Hosted at the Sahyadri College of Engineering and Management grounds, TerraGlide is a unique competition that challenges participants to design, build, and pilot hovercraft models through an intricate racetrack filled with obstacles and time trials.",
//     smallDesc: "The teams shall be competing for a prize pool of ₹25000",
//     format: {
//       "Problem Statement:": [
//         "A hovercraft is a vehicle that floats on a cushion of high-pressurized air and propels itself on this air cushion using a thrust-producing mechanism. Participants are required to design and build a remotely operated electric RC Hovercraft to navigate a given course. The craft that can complete the track in the shortest time ( Round 1 ) and secure the maximum points from the obstacle course ( Round 2 ) will be declared the winner. ",
//       ],
//       "Round 1: Time Trial :": [
//         "With a set time of 8 minutes, teams embark on a time trial race. The total number of laps done in this time interval will be considered. Teams with the maximum number of laps will be declared as the winner.",
//         "2 attempts will be awarded for each team in this round.",
//         "Each lap will have a weightage of 10 Points ie. (n*10) where n is the number of laps covered.",
//         "A team must reach the halfway point to earn points for a lap; otherwise, no points are awarded.",
//         "50% of the scores from this round will be considered.",
//         "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
//         "Each team will have 2 attempts for this round.",
//       ],
//       "Round 2: Navigating Obstacle Havoc:": [
//         "With a set time of 8 minutes, teams embark on a time trial race. The total number of laps done in this time interval will be considered. Teams with the maximum number of laps will be declared as the winner.",
//         "2 attempts will be awarded for each team in this round.",
//         "Each lap will have a weightage of 10 Points ie. (n*10) where n is the number of laps covered.",
//         "A team must reach the halfway point to earn points for a lap; otherwise, no points are awarded.",
//         "50% of the scores from this round will be considered.",
//         "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
//         "Each team will have 2 attempts for this round.",
//       ],
//       "Objective:": [
//         "In this round, teams are challenged to navigate a demanding obstacle course using their hovercraft within a strict time limit of 8 minutes. The total number of points that can be scored in this round is 100. Each team will be provided with 2 attempts",
//       ],
//       "Obstacles Points Assignment:": [
//         "Jelly Stone (15 points): Teams must skillfully navigate their hovercraft over a section of jelly stones without causing any damage or getting stuck.",
//         "Pool of Water (30 points): Successfully traversing through a pool of water will earn teams the maximum points.",
//         "Sandpit (10 points): Teams need to cross a sandy area while maintaining control and speed.",
//         "Sea-saw (20 points): Hovercrafts must carefully balance on a sea-saw structure without tipping over or causing a collision.",
//         "Zig Zag Stone (Hurdles) (25 points): Teams will face a zig-zag pattern of stone hurdles, and they must navigate through them with precision.",
//         "Note: Teams are allowed to skip any of the obstacles if they feel that it can damage their hovercraft, no points will be given for attempting the obstacle.",
//       ],
//       "Scoring Guildlines:": [
//         "Points will be awarded based on the successful completion of each obstacle as specified above.",
//         "Points will be deducted (-3 points) if any part of the hovercraft touches certain corners or boundaries of the course.",
//         "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
//         "The team can take any number of laps until the timer ticks out of time.",
//         "50% of the score is taken into consideration.",
//       ],

//       "Winner Determination:": [
//         "The team with the highest aggregate score, which includes points earned from previous rounds, will be declared the winner of the hovercraft event. This round's points will contribute significantly to the final score, so teams must balance speed and precision while tackling the obstacles to secure victory.",
//       ],
//       "Specification for the hovercraft:": [
//         "The hovercraft will undergo the following inspection on the event day.",
//         "The l*b*h of the hovercraft needs to be under (25*25*25)cm and needs to fit in a square of 25 cm.",
//         "Brushless motors with a rating of no more than 2700 KV can be used. Participants should have the Motor model with them to prove the KV value when asked to do so.",
//         "ESC's current ratings should not exceed 40 A.",
//         "The hovercraft should be powered by rechargeable batteries only.",
//         "A power supply (battery) above 12 Volts (3s) cannot be used.",
//         "The hovercraft must not have any hazardous or sharp elements that harm other hovercrafts.",
//         "Violation of any of the above rules will lead to the disqualification of the team/individual.",
//       ],
//     },
//     rules: [
//       "All decisions about scoring, gameplay, and timing made by the coordinators and judges are final.",
//       "All the decisions taken by the judges or the volunteers will be considered and no argument will be allowed.",
//       "Any changes in the rules will be mentioned on the website.",
//       "Teams failing to abide by the rules will lead to disqualification.",
//       "The event is open to all engineering students from any college or university.",
//       "A team size of a maximum of 3 members is allowed. Individual entries are also allowed.",
//       "Graduates from the year 2023 are allowed to participate in this event.",
//       "The model can be fabricated using foam, wood, coroplast (sunpack), or 3D printed (PLA or resin filament-based). Even though the possibilities are not limited.",
//       "Participants are responsible for the safety of their hovercraft and should take adequate measures to prevent any damage.",
//       "The use of any hazardous material is strictly prohibited.",
//       "Participants must make all parts of the hovercraft by themselves. i.e. usage of ready-made hovercrafts is strictly prohibited.",
//       "A team must use only one model at a time throughout the competition. However, if damaged, models can be fabricated, if material permits. In case of any damage to the craft, minor modifications are allowed. The modifications need to be specified with the event organizer before executing.",
//       "Violation of any of the above rules will lead to disqualification of the team or individual.",
//       "Only 3 people are allowed near the arena where the pilot is allowed to stand in a designated spot without following the hovercraft, no team member is allowed to follow the hovercraft.",
//       "In the case of individual participants, he is free to ask for help from any volunteers present during the event, adhering to all penalties mentioned above.",
//       "All these rules are subject to changes and will be mentioned on the website and through the Instagram page.",
//       "Please be aware that the organizer's decision is ultimately binding in all situations.",
//     ],
//     contactDetails: [
//       {
//         name: "ANUP PAI",
//         phoneNumber: "+91 919731189986",
//       },
//     ],
//     link: "",
//   },
//   {
//     type: "Technical",
//     name: "SKY DIVE",
//     day: "2",
//     fee:900,
//     time: "9 AM",
//     venue: "CANTEEN GROUND",
//     date: "9th Dec",
//     maxlimit: 5,
//     mode: "online",
//     image: img,
//     prize: "₹70000",
//     registrations: [
//       "Spot registrations are available.",
//       "Registration fee: ₹ XXXX per team",
//     ],
//     teamReq: [
//       "Maximum 5 members in a team.",
//       "Participation allowed only for college students.",
//     ],
//     desc: "Team Challengers of Sahyadri College of Engineering and Management, Mangalore invites all university students to participate in Aerophilia ‘23. The contest will provide a real-world aircraft design experience for engineering students by allowing them to validate their analytical skills. Student teams will design, fabricate, and demonstrate the flight capabilities of an unmanned, electric-powered, radio-controlled aircraft that can best meet the specified mission profile. The goal is a balanced design possessing good, demonstrated flight handling qualities, and practical and affordable manufacturing requirements. Check the rules package carefully as items and approaches that were legal in past years may not be legal for this contest year. Only the contents of this year's Rules package along with the current FAQ and Q&A documents hold bearing on the requirements and/or allowances for the current contest year. It is the responsibility of the teams to know and follow all provided rules, the FAQ and Q&A, and all contest day briefings. Winning teams will receive prizes worth ₹70,000. ",
//     smallDesc:
//       "The team with the best Report Score will receive a prize of ₹5,000.",
//     format: {
//       "FLIGHT LINE COURSE:": [
//         "The orientation (direction) of the flight course will be adjusted based on the prevailing winds as determined by the Flight Line Judge. The flight course will be positioned to maintain the greatest possible safety for personnel and facilities. The nominal flight course will be uploaded on the official Aerophilia website.",
//         "Note: The final flight course may vary depending on the weather and other physical aspects.",
//       ],
//       "DESIGN REPORT/ABSTRACT SUBMISSION:": [
//         "Design Reports will be submitted online via email to submission@aerophilia.in The design report submission period OPENS on 10.10.2023 Indian Standard Time. The design report must be submitted by 23:59 Indian Standard Time on 15.11.2023.",
//         "Reports will be judged “as received”. No corrections/additions/changes will be allowed by the organizers so check your reports carefully before submitting them. Once a Report is submitted, no changes are allowed. Submission of Reports is electronic only (no hard copy required). The details for the electronic format and submission are at the end of the report section in this rules document.",
//       ],
//       "MISSION AND VEHICLE DESIGN:": [
//         "Mission 1 - Spot landing",
//         "Mission 2 - Manoeuvring",
//         "Mission 3 - Stunt round",
//       ],
//       "MISSION SEQUENCE:": [
//         "Aircraft must be capable of performing all required missions.",
//         "Missions must be flown in order.",
//         "A new mission cannot be flown until the team has obtained a successful score for the preceding mission.",
//         "The aircraft must be flown in the same configuration for all three missions. For example, if any pod is carried under the wing, then that pod must be flown in all three missions.",
//         "The aircraft must complete a successful landing at the end of each mission. If the aircraft takes any serious damage during the landing, it would be considered a crash landing.",
//       ],
//       "MISSIONS:": ["Below is the list of missions"],

//       " Mission 1 - Spot landing:": [
//         "Teams must take off their plane, fly it for at least 30 seconds, and land it properly at the designated area, i.e., a circle of X meters in diameter.",
//         "No part of the plane should be outside the circle.",
//         "If the teams land within the circle but exceed the time limit, then only 1 point will be awarded.",
//         "If the plane crashes, then 5 points will be deducted.",
//         "The pilot is allowed to move anywhere in the arena during Mission 1.",
//         "There will be a 2-minute flight window for this mission.",
//         "Time starts when the aircraft throttle is advanced in the first attempt.",
//         "Teams must complete a successful landing to obtain a score and successfully complete Mission 1.",
//         "Scoring: M1 = 20 for a successful mission (10 for a successful flight and 10 for landing in the specified area).",
//       ],
//       "Mission 2 - Hoop Maneuvering": [
//         "The airplane must maneuver through a series of hoops, which will be shown on the day of the event.",
//         "The pilot is not allowed to move around and must stay in a fixed spot in the arena.",
//         "A time window of 5 minutes will be provided, during which the teams can complete any number of laps of the set course.",
//         "The scoring will take place depending on the number of laps completed.",
//         "In mission 2, a lap will be considered successful only when the airplane passes through all the hoops in the given chronological order.",
//         "Teams must complete a successful landing to obtain a score and successfully complete Mission 2.",
//         "Scoring: M2 = 10 * n where n stands for the number of successful laps.",
//       ],
//       "Mission 3 - Stunts": [
//         "Evaluation will be based on the time of flight and the number of stunts performed by the participant.",
//         "Stunts' performance will be the first criterion for evaluation.",
//         "Time of flight will be considered only if 2 or more teams get equal marks. The fastest team will be considered.",
//         "If a plane crashes, then only 70 percent of points earned from stunts will be awarded.",
//         "A team can perform any number of stunts according to their abilities.",
//         "Evaluation Scheme: Total points = Stunt points (280 max.)",
//       ],

//       "Stunts (freestyle):": [
//         "Roll along the horizontal axis (for at least 10 seconds) [5 points]",
//         "Roll along the vertical axis (for at least 5 seconds) [10 points]",
//         "Horizontal 8 or infinity sign through the hoops [10 points]",
//         "Maximum score for stunt flying is 40 points.",
//         "And any stunts mentioned above through the loop like infinity sign stunt will be awarded bonus points.",
//       ],
//     },
//     rules: [
//       "The maximum wingspan allowed is 1.5 metres.",
//       "3D stunt plane models can be used.",
//       "All models must be self-built. No ready-to-fly models can be used.",
//       "Teams flying out of the boundary will be eliminated.",
//     ],
//     judgingCriteria: [
//       "All vehicles will undergo a technical inspection by a designated contest tech inspector before being allowed to make any competition flight. All the decisions taken by the Tech inspector will be considered final.",
//     ],
//     contactDetails: [
//       {
//         name: "Sushan Shetty",
//         phoneNumber: "+91 6360298756",
//       },
//       {
//         name: "K Anup Pai",
//         phoneNumber: "+91 9731189986",
//       },
//     ],
//     link: " ",
//   },
// ];

export const eventData = [
  {
    type: "Technical",
    name: "UI BATTLES",
    day: "1",
    time: "1.30 PM",
    venue: "APTI LAB OR DEPARTMENT LAB",
    date: "8th Dec",
    maxlimit: 2,
    mode: "online",
    image: ui,
    prize: "₹10,000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 300 per team",
    ],
    teamReq: [
      "Each team should consist of a maximum of 2 members.",
      "Solo participation is also allowed.",
      "Team members must be of the same school or college.",
      "Participants should get their school/college ID card.",
      "Any number of teams from a school/college is allowed.",
    ],
    desc: "Hello coders! Are you ready for an exciting challenge that aligns with your passion for web development. Welcome to the Web Dev code the logic & Page Cloning Challenge, where your fundamental coding skills will be put to the ultimate test.",
    smallDesc: "Code Clone Conquer",
    format: {
      "Round-1  CODE THE LOGIC :": [
        "Teams will be given a set of HTML snippets. Each snippet will have an associated description indicating the task that needs to be performed. Participants have to choose the correct javascript code to satisfy the functionality demanded.(MCQ type).There will be only one correct option",
        "There will be no elimination in this round",
        "Teams will be scored on the number of correct options they select",
        " If 2 teams get the same score, then the team which submitted first will be given higher priority.(only in case there is a tie after the second round)",
        "This score will be carried forward for the next round",
        "It will carry only 30% of weightage",
      ],
      "Round-2 - PAGE CLONING CHALLENGE :": [
        "Teams will be provided with a figma design which they have to clone using HTML, CSS and javascript only..",
        " Teams have to clone the figma design in the specified duration",
        "Teams will be evaluated based on how closely their web page aligns with the provided figma design",
        "Participants will be provided with internet to refer only in this round",
        "It will carry 70% of weightage",
      ],
    },
    rules: [
      "Usage of cell phones or any other electronic devices is prohibited. ",
      "Communication with any other team during the event is prohibited, both in online and offline mode.",
      "The Organizer's decision will be final.",
      "These rules are subjected to change.",
    ],
    judgingCriteria: [
      "The team with the maximum total score from both the rounds will be declared the winner. i.e, after adding the score from the first round and the second round whichever team has higher score that team will be declared the winner",
    ],
    contactDetails: [
      {
        name: "Babith",
        phoneNumber: "+91 8971206807",
      },
      {
        name: "Srajan",
        phoneNumber: "+91 8050215589 ",
      },
    ],
    link: "https://drive.google.com/file/d/1HfnTF2TSSlr_fgSh-7He0C_Y4_cxbzon/view?usp=sharing",
  },
  {
    type: "Technical",
    name: "LINE FOLLOWER",
    day: "1",
    time: "10.30 AM",
    venue: "2nd Floor Seminar Hall",
    date: "8th Dec",
    maxlimit: 5,
    mode: "online",
    image: line,
    prize: "₹10000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 500 per team",
    ],
    teamReq: [
      "All the team members must be full-time students at an accredited University/College/School.",
      "There are no restrictions on the number of teams from the same Institute.",
      "The team should contain 3-5 members in total.",
    ],
    desc: "A competition played by one or two teams at a time, with each team consisting of one wireless bot. The objective is to build a bot capable of completing various challenges along the way in the shortest period of time. The competition will test the robot's speed, accuracy, and ability to handle complex track layouts including intersections, curves, and junctions",

    smallDesc: "Let's Race!",
    format: {
      "Round-info": [
        "The competition will consist of 3 rounds.",
        "Each round will have a different map which will be disclosed on the day of the event.",
        "Round-specific rules will be explained just before the start of that particular round.",
        "All the rounds will have a black line/trajectory on a white arena.",
      ],
    },
    rules: [
      "Two or more teams cannot share one robot; moreover, the robot cannot be ready-made.",
      "A practice arena will be provided, but no test/practice on the main arena will be allowed.",
      "Once a robot has crossed the start line, it must remain fully autonomous.",
      "The width of the trajectory of the arena is approximately 3 cm.",
      "Participants should arrange their own batteries, and the power supply must be on board.",
      "The robot must remain intact until results are announced.",
      "The judges' verdict is considered final, and no arguments will be entertained.",
    ],
    judgingCriteria: [
      "Score = (Time taken to reach the finish line)+(penalty)",
    ],
    contactDetails: [
      {
        name: "AKSHAY SHET",
        phoneNumber: "+91 9449384765",
      },
    ],
    link: "https://drive.google.com/file/d/1cH0LcMKuQwna7rcmB2B61KOL6uz2Qn4k/view?usp=sharing",
  },
  {
    type: "Technical",
    name: "CAD-CARNIVAL",
    day: "1",
    time: "1.30 PM",
    venue: "CAD LAB(Mechanical Department)",
    date: "8th Dec",
    maxlimit: 3,
    mode: "online",
    image: cad,
    prize: "₹5000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹300 per team",
    ],
    teamReq: [
      "All the team members must be full-time students at an accredited University/College/School.",
      "Students from multiple Colleges can form a team.",
      "There are no restrictions on the number of teams from the same Institute.",
      "The team should have 2-3 members in total.",
      "Individual participation is allowed",
      "A team can have a maximum of 3 participants",
      "Each participant may only be a part of one team.",
    ],

    desc: "The competition involves creating a replica of a CAD model enclosed within a cube provided to the contestants. The model given will only have TWO dimensions at the beginning of the event. The other dimensions will be provided after a specific interval of time, one by one. The rest of the dimensions must be self-estimated.The team with the closest resembling CAD model to the reference model wins",
    smallDesc: "CAD competetion",
    format: {
      "Round-info": [
        "The CAD Model enclosed in a cube will be presented on the screen.",
        "A copy of the model having a top, front, and isometric view with no dimensions will be given in hardcopy to each team.",
        "The Model on the screen will have only 2 dimensions for the beginning.",
        "The other dimension will be provided with a time gap of 1 hour or 30 mins, depending on the importance of the dimension.",
        "Only 75% of the dimensions are provided until the end of the event.",
        "Material specifications will be given at the last hour of the competition.",
        "Contestants can make the model on the given PC or on their own laptop.",
      ],
    },
    rules: [
      "Each team is provided with one PC having Solidworks/ fusion360 installed",
      "The organizing team holds all the authority to disqualify the team without warning and without stating the reason. This decision is final and binding on the participants.",
      "Having their own laptop is compulsory as no more than one PC is provided.",
      "The event has a duration of 4 hours, and contestants are allowed a 30-minute break 2 hours from the start.",
      "The Scoring Criteria - Total points that can be awarded:  10 distributions-4 points for getting the weight of the model, 4 points for the correct dimension ,2 points for rendering of the model",
    ],
    judgingCriteria: [
      "The team should not try to copy the dimensions from the other teams.",
      "Any team found practicing malpractice by sharing information with other teams or trying to copy the dimensions will be disqualified.",
      "The organizing team retains the authority to disqualify a team without prior notice or the need to provide a specific explanation.",
    ],
    contactDetails: [
      {
        name: "ROHAN BALAMKAR",
        phoneNumber: "+91 8618983737 ",
      },
    ],
    link: "https://drive.google.com/file/d/1Q0nudNNeCffyRwJ6Wq_K1poJYO-KLKeC/view?usp=sharing",
  },
  {
    type: "Technical",
    name: "CODE QUEST",
    day: "2",

    time: "9.30 AM",
    venue: "Apti lab or Department lab",
    date: "9th Dec",
    maxlimit: 3,
    mode: "online",
    image: code,
    prize: "₹10000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 300 per team",
    ],
    teamReq: [
      "All the team members must be full-time students at an accredited University/College/School.",
      "Students from multiple Colleges can form a team.",
      "There are no restrictions on the number of teams from the same Institute.",
      "The team can have 3 members in total",
      "Individual Participation is also allowed",
      "Each participant may only be a part of one team",
      "Participants should get their school/college ID card",
    ],
    desc: "Want to show off your coding skills? Then you have come to the right place. Here you can show your skills by completing the given challenges. Face against your peers to test your current level. Make sure to keep your foundations of coding skills strong.",
    smallDesc: "Compete Win Prove",
    format: {
      "Round-1  THE PRELIMINARY TEST :": [
        "In this round, 25 MCQ questions related to computer science will be given to the participants, who are supposed to solve them within 25 mins.",
      ],
      "Round-2 :": [
        "A group of codes will be shared to all the teams (5 questions). The participants will have to find the total number errors in the given code (in python or C or C++) and write the line number in which the error is present. Points will be allocated to the teams based on the number of errors they find. Teams will have to complete the event within the given time limit.",
      ],
      "Round-3 :": [
        "In this round, 4 coding questions will be given to the participants, who are supposed to solve the problem within a given time limit. The participants can code in one of the languages from the given options (python/C/C++).",
      ],
    },
    rules: [
      "Communication with other teams is not allowed during the event.",
      "No external electronic device is allowed to be used during the event.",
      "The Organizer's decision will be final.",
      "In case of foul play the team will be disqualified.",
    ],
    judgingCriteria: [
      "Winner will be decided by the number of points each team has earned.",
      "In case of two teams having the same points, a tie-breaking round will be conducted, where teams will be given 5-Questions, whichever team completes it fast with most correct answers will be considered.",
    ],
    contactDetails: [
      {
        name: "ANUDEEP K K",
        phoneNumber: "+91 8762339086 ",
      },
      {
        name: "Sankshipth Shetty",
        phoneNumber: "+91 6362531671",
      },
    ],
    link: "https://drive.google.com/file/d/1ACs6OlKEeDG7W43M4zRuc2fqxgduLEXc/view?usp=sharing",
  },

  {
    type: "Technical",
    name: "MOMENTUM",
    day: "2",
    time: "9.30 AM",
    venue: "Ground beside back cricket ground ",
    date: "9th Dec",
    maxlimit: 4,
    mode: "online",
    image: momentum,
    prize: "₹5000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 400 per team",
    ],
    teamReq: [
      "Team should not exceed more than 4 people.",
      "Team members should be from the same institution.",
      "Each participant may only be a part of one team.",
      "Any number of teams from a school/college is allowed.",
    ],
    desc: "How exhilarating will it be to build and fly your own rocket? Get ready to launch into a world where innovation takes flight, and engineering prowess meets the power of H2O! Join us as we witness rockets of all shapes and sizes, each meticulously crafted to soar to the sky, powered only by the might of water and the brilliance of engineering minds. Welcome to the most exhilarating event of the year, where creativity soars higher than ever before, MOMENTUM - Aerophilia23's Water Rocket Competition! ",
    smallDesc: "Ride the tide, laws applied!",
    format: {
      task: [
        "Teams are required to construct a water propelled rocket pressurized with air using bottles. These will be then tested for their efficiency and working against each other.",
      ],
      specifications: [
        "The total capacity of the rocket shouldn't exceed 2.5 liters.",
        "Boosters and staging of the rocket are allowed.",
        "Total capacity of the booster and stage should not exceed 1 liter. If boosters and stage are included, the total capacity of the rocket shouldn’t exceed 3.5 liters.",
      ],
      "Round-1  How Far?:": [
        "In this round, teams must launch the rockets and try to obtain the maximum score.",
        "Teams will get 10 points for each 10 meters of the rocket's horizontal flight distance",
        "Rockets which don't go further than 20 meters will not fetch any points",
        "Rockets which go more than 100 meters will get 20 points for consecutive 10 meters.",
      ],
      "Round-2 - Hit the target :": [
        "In this round, the rocket launched should hit an area marked at a distance of 65m.",
        "The target area will be in circular shape with three regions.",
        "Innermost region of diameter 10 meters (30 points)",
        "Middle region of diameter 15 meters (20 points)",
        " Outermost region of diameter 20 meters (10 points)",
        "Rockets that do not touch the target will receive a negative score of 20 points.",
      ],
    },
    rules: [
      "Teams from the same school are not allowed to exchange their equipment or help the other team.",
      "Launching angle to be decided by the participating team.",
      "Usage of Electronic systems, Fireworks, Explosives, or parachutes is restricted.",
      "Working fluid is water and only it should be used in the propulsion of the rocket; no other things or systems should be used.",
      "Boosters and staging are allowed.",
      "Ground inspection will be done.",
      "Teams will get 2 tries in each round.",
      "Range (in meters) and time of flight (in seconds) will be measured by the organizers.",
      "Only members of the participating team will be allowed to launch.",
    ],
    judgingCriteria: [
      "All decisions about scoring, gameplay, and timing made by the coordinators and judges are final.",
      "All the decisions taken by the judges or the volunteers will be considered and no argument will be allowed.",
      "Any changes in the rules will be mentioned on the website.",
      "Teams failing to abide by the rules will lead to disqualification.",
    ],
    contactDetails: [
      {
        name: "Thejaswi",
        phoneNumber: "+91 8296584492 ",
      },
    ],
    link: "https://drive.google.com/file/d/1Xvq43Ay93aYlm2B9u7RFyW1SFe6SBdDO/view?usp=drive_link",
  },
  {
    type: "Technical",
    name: "TERRAGLIDE",
    day: "1 and 2 ",

    time: "11 AM",
    venue: "Canteen ground ",
    date: " 8th and 9th Dec",
    maxlimit: 4,
    mode: "online",
    image: terraglide,
    prize: "₹25000",
    registrations: [
      "Maximum 4 members in a team.",
      "Participation allowed for school & college students with valid ID proof.",
    ],
    teamReq: [
      "There are no specific requirements for the team or the team members.",
    ],
    desc: "Welcome to the exhilarating event of Aerophilia’23 TerraGlide, an event that pushes the boundaries of engineering creativity and precision. Hosted at the Sahyadri College of Engineering and Management grounds, TerraGlide is a unique competition that challenges participants to design, build, and pilot hovercraft models through an intricate racetrack filled with obstacles and time trials.",
    smallDesc: "Glide to Glory",
    format: {
      "Problem Statement:": [
        "A hovercraft is a vehicle that floats on a cushion of high-pressurised air and propels itself on this air cushion using a thrust-producing mechanism. Participants are required to design and build a remotely operated electric RC Hovercraft to navigate a given course. The craft that can complete the track in the shortest time ( Round 1 ) and secure the maximum points from the obstacle course ( Round 2 ) will be declared the winner. ",
      ],
      "Round 1: Time Trial :": [
        "With a set time of 8 minutes, teams embark on a time trial race. The total number of laps done in this time interval will be considered. Teams with the maximum number of laps will be declared as the winner.",
        "2 attempts will be awarded for each team in this round.",
        "Each lap will have a weightage of 10 Points ie. (n*10) where n is the number of laps covered.",
        "A team must reach the halfway point to earn points for a lap; otherwise, no points are awarded.",
        "50% of the scores from this round will be considered.",
        "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
        "Each team will have 2 attempts for this round.",
      ],
      "Round 2: Navigating Obstacle Havoc:": [
        "With a set time of 8 minutes, teams embark on a time trial race. The total number of laps done in this time interval will be considered. Teams with the maximum number of laps will be declared as the winner.",
        "2 attempts will be awarded for each team in this round.",
        "Each lap will have a weightage of 10 Points ie. (n*10) where n is the number of laps covered.",
        "A team must reach the halfway point to earn points for a lap; otherwise, no points are awarded.",
        "50% of the scores from this round will be considered.",
        "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
        "Each team will have 2 attempts for this round.",
      ],
      "Objective:": [
        "In this round, teams are challenged to navigate a demanding obstacle course using their hovercraft within a strict time limit of 8 minutes. The total number of points that can be scored in this round is 100. Each team will be provided with 2 attempts",
      ],
      "Obstacles Points Assignment:": [
        "Jelly Stone (15 points): Teams must skillfully navigate their hovercraft over a section of jelly stones without causing any damage or getting stuck.",
        "Pool of Water (30 points): Successfully traversing through a pool of water will earn teams the maximum points.",
        "Sandpit (10 points): Teams need to cross a sandy area while maintaining control and speed.",
        "Sea-saw (20 points): Hovercrafts must carefully balance on a sea-saw structure without tipping over or causing a collision.",
        "Zig Zag Stone (Hurdles) (25 points): Teams will face a zig-zag pattern of stone hurdles, and they must navigate through them with precision.",
        "Note: Teams are allowed to skip any of the obstacles if they feel that it can damage their hovercraft, no points will be given for attempting the obstacle.",
      ],
      "Scoring Guildlines:": [
        "Points will be awarded based on the successful completion of each obstacle as specified above.",
        "Points will be deducted (-3 points) if any part of the hovercraft touches certain corners or boundaries of the course.",
        "If a team relocates their hovercraft, they must remain idle for 3 seconds as a penalty.",
        "The team can take any number of laps until the timer ticks out of time.",
        "50% of the score is taken into consideration.",
      ],

      "Winner Determination:": [
        "The team with the highest aggregate score, which includes points earned from previous rounds, will be declared the winner of the hovercraft event. This round's points will contribute significantly to the final score, so teams must balance speed and precision while tackling the obstacles to secure victory.",
      ],
      "Specification for the hovercraft:": [
        "The hovercraft will undergo the following inspection on the event day.",
        "The l*b*h of the hovercraft needs to be under (25*25*25)cm and needs to fit in a square of 25 cm.",
        "Brushless motors with a rating of no more than 2700 KV can be used. Participants should have the Motor model with them to prove the KV value when asked to do so.",
        "ESC's current ratings should not exceed 40 A.",
        "The hovercraft should be powered by rechargeable batteries only.",
        "A power supply (battery) above 12 Volts (3s) cannot be used.",
        "The hovercraft must not have any hazardous or sharp elements that harm other hovercrafts.",
        "Violation of any of the above rules will lead to the disqualification of the team/individual.",
      ],
    },
    rules: [
      "All decisions about scoring, gameplay, and timing made by the coordinators and judges are final.",
      "All the decisions taken by the judges or the volunteers will be considered and no argument will be allowed.",
      "Any changes in the rules will be mentioned on the website.",
      "Teams failing to abide by the rules will lead to disqualification.",
      "The event is open to all engineering students from any college or university.",
      "A team size of a maximum of 3 members is allowed. Individual entries are also allowed.",
      "Graduates from the year 2023 are allowed to participate in this event.",
      "The model can be fabricated using foam, wood, coroplast (sunpack), or 3D printed (PLA or resin filament-based). Even though the possibilities are not limited.",
      "Participants are responsible for the safety of their hovercraft and should take adequate measures to prevent any damage.",
      "The use of any hazardous material is strictly prohibited.",
      "Participants must make all parts of the hovercraft by themselves. i.e. usage of ready-made hovercrafts is strictly prohibited.",
      "A team must use only one model at a time throughout the competition. However, if damaged, models can be fabricated, if material permits. In case of any damage to the craft, minor modifications are allowed. The modifications need to be specified with the event organizer before executing.",
      "Violation of any of the above rules will lead to disqualification of the team or individual.",
      "Only 3 people are allowed near the arena where the pilot is allowed to stand in a designated spot without following the hovercraft, no team member is allowed to follow the hovercraft.",
      "In the case of individual participants, he is free to ask for help from any volunteers present during the event, adhering to all penalties mentioned above.",
      "All these rules are subject to changes and will be mentioned on the website and through the Instagram page.",
      "Please be aware that the organizer's decision is ultimately binding in all situations.",
    ],
    contactDetails: [
      {
        name: "Amog",
        phoneNumber: "+91 6363128809",
      },
    ],
    link: "https://drive.google.com/file/d/17FeLwu8IjGUzEd_Y60xDvnfVMOyBcR6v/view?usp=sharing",
  },
  {
    type: "Technical",
    name: "SKY DIVE",
    day: "1 and 2",
    time: "11 AM",
    venue: "BACK GROUND",
    date: "8th and 9th Dec",
    maxlimit: 5,
    mode: "online",
    image: sky,
    prize: "₹75000",
    registrations: ["Registration fee: ₹ 2500 per team"],
    teamReq: [
      "Maximum 5 members in a team.",
      "Participation allowed for school & college students with valid ID proof.",
    ],
    desc: "Team Challengers of Sahyadri College of Engineering and Management, Mangalore invites all university students to participate in Aerophilia ‘23. The contest will provide a real-world aircraft design experience for engineering students by allowing them to validate their analytical skills. Student teams will design, fabricate, and demonstrate the flight capabilities of an unmanned, electric-powered, radio-controlled aircraft that can best meet the specified mission profile. The goal is a balanced design possessing good, demonstrated flight handling qualities, and practical and affordable manufacturing requirements. Check the rules package carefully as items and approaches that were legal in past years may not be legal for this contest year. Only the contents of this year's Rules package along with the current FAQ and Q&A documents hold bearing on the requirements and/or allowances for the current contest year. It is the responsibility of the teams to know and follow all provided rules, the FAQ and Q&A, and all contest day briefings. Winning teams will receive prizes worth ₹70,000.  The team with the best Report Score will receive a prize of ₹5,000.",

    smallDesc: "The sky's calling!",
    format: {
      "FLIGHT LINE COURSE:": [
        "The orientation (direction) of the flight course will be adjusted based on the prevailing winds as determined by the Flight Line Judge. The flight course will be positioned to maintain the greatest possible safety for personnel and facilities. The nominal flight course will be uploaded on the official Aerophilia website",
        "Note: The final flight course may vary depending on the weather and other physical aspects.",
      ],
      "DESIGN REPORT/ABSTRACT SUBMISSION:": [
        "Design Reports will be submitted online via email to submission@aerophilia.in. The design report must be submitted by 23:59 Indian Standard Time on 20.11.2023.",

        "Reports will be judged “as received”. No corrections/additions/changes will be allowed by the organisers so check your reports carefully before submitting them. Once a Report is submitted, no changes are allowed. Submission of Reports is electronic only (no hard copy required). The details for the electronic format and submission are at the end of the report section in this rules document.",
      ],
      "MISSION AND VEHICLE DESIGN:": [
        "Mission 1 - Spot landing",
        "Mission 2 - Manoeuvring",
        "Mission 3 - Stunt round",
      ],
      "MISSION SEQUENCE:": [
        "Aircraft must be capable of performing all required missions.",
        "The Missions must be flown in order.",
        "A new mission cannot be flown until the team has obtained a successful score for the preceding mission.",
        "The aircraft must be flown in the same configuration for all three missions. For example, if any pod is carried under the wing, then that pod must be flown in all three missions.",
        "The aircraft must complete a successful landing at the end of each mission. If the aircraft takes any serious damage during the landing, it would be considered a crash landing.",
      ],
      "MISSIONS:": ["Below is the list of missions"],

      " Mission 1 - Spot landing:": [
        "Teams must take off their plane, fly it for at least 120 seconds, and land(touchdown) it properly at the designated area, i.e., a circle of 3 meters in diameter.",
        "No time limit for this round.",
        "If the plane crashes, then 5 points will be deducted.",
        "The pilot is allowed to move anywhere in the arena during Mission 1",
        "Time starts when the aircraft throttle is advanced in the first attempt.",
        "Teams must complete a successful landing to obtain a score and successfully complete mission 1",
        "Basically, Takeoff + 2 Minutes fly + Landing",
        "M1 = 20 for a successful mission. (10 for a successful flight and 10 for landing in the specified area)",
      ],
      "Mission 2 - Hoop Maneuvering": [
        "The airplane must maneuver through a series of hoops, which will be shown on the day of the event.",
        "The pilot is not allowed to move around and must stay in a fixed spot in the arena.",
        "A time window of 5 minutes will be provided, during which the teams can complete any number of laps of the set course.",
        "The scoring will take place depending on the number of laps completed.",
        "In mission 2, a lap will be considered successful only when the airplane passes through all the hoops in the given chronological order.",
        "Teams must complete a successful landing to obtain a score and successfully complete Mission 2.",
        "Scoring: M2 = 10 * n where n stands for the number of successful laps.",
      ],
      "Mission 3 - Stunts": [
        "Evaluation will be based on the time of flight and the number of stunts performed by the participant.",
        "Time duration allocated for each team is 10 minutes.",
        "Stunts' performance will be the first criterion for evaluation",
        "Time of flight will be considered only if 2 or more teams get equal marks. The fastest team will be considered.",
        "If a plane crashes, then only 70 percent of points earned from stunts will be awarded.",
        "A team can perform any number of stunts according to their abilities",
        "Evaluation Scheme: Total points = Stunt points",
        "Maximum points awarded in this round is 50 points.",
        "No stunt can be performed more than once.",
      ],
    },
    rules: [
      "The maximum wingspan allowed is 1.5 metres.",
      " Landing Gear is compulsory for all rounds, Team without landing gear will have point penalty during inspection",
      "All models must be self-built. No ready-to-fly models can be used.",
      "Teams flying out of the boundary will be eliminated.",
      "Teams crossing the spectator boundary will be disqualified from the event.",
      "The verdict of judge's and organisers is final. ",
      "The verdict of judge's and organizers is final",
      "Rules will be properly explained before each round.",
    ],
    judgingCriteria: [
      "All vehicles will undergo a technical inspection by a designated contest tech inspector before being allowed to make any competition flight. All the decisions taken by the Tech inspector will be considered final.Inspection will be there after each round",
    ],
    contactDetails: [
      {
        name: "Sushan Shetty",
        phoneNumber: "+91 6360298756",
      },
      {
        name: "K Anup Pai",
        phoneNumber: "+91 9731189986",
      },
    ],
    link: "https://drive.google.com/file/d/1O768HT2h3eGFOQjENIAFY2srwYbbfA1f/view?usp=sharing",
  },
  {
    type: " Non Technical",
    name: "FRAMES",
    day: "1 and 2",
    fee: 200,
    time: "Throughout the day",
    venue: "",
    date: "8th and 9th Dec",
    maxlimit: 1,
    mode: "online",
    image: frames,
    prize: "₹3000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 200",
    ],
    teamReq: [
      "Individual Registration.",
      "Participants can use either a professional camera or a phone for the competition.",
    ],
    desc: "Frames is a photography contest where photographers can showcase their skills by submitting stunning images captured during Aerophilia '23. You don't need extensive Photoshop expertise or a high-end professional camera to capture great photos. With basic photography techniques, you can create exquisite photos, even using just your smartphone.",
    smallDesc: "Capture timeless memories",
    format: {
      "Rules and Regulations :": [
        "The competition will be conducted for two days of the event.",
        "The competition is strictly for Photos and not Videos.",
        "Photos must be your own work.",
        "The submitted photo must not be larger than 10MB.",
        "Only digital manipulation that does not alter the original content of the image is allowed. This includes, but is not limited to, cropping, Levels/Curves adjustments, minor dodging and burning, and conversion to greyscale or sepia.",
        "The 3 best photos must be submitted through email as a Google Drive file.",
        "Each participant must select one photo and post it on their Social Media tagging @aerophilia_2023 and @sahyadri_college and using the #Aerophilia_2023 each day for the span of the event.",
        "The winners will be announced on the ﬁnal day of the event.",
        " Each participant will get an option to submit all their photos or even videos shot during the event on the ﬁnal day.",
      ],
    },
    rules: [
      "By entering this competition, you grant the organizers the right to use or publish your name, work, and/or likeness without further compensation. ",
      "The organizers are not responsible for any damage to the camera equipment caused during the event.",
      "The contestants are requested to comply with the organizers in this regard, a violation of which will lead to immediate disqualiﬁcation.",
      "These rules are subjected to change.",
    ],
    judgingCriteria: [
      "The winner will be selected on the basis of",
      "1. Composition",
      "2 .Lighting",
      "3.Emotion Captured",
      "4.Originality",
    ],
    contactDetails: [
      {
        name: "VIVIN LOBO",
        phoneNumber: "+91 78924 28715",
      },

      {
        name: "SATHWIK SHETTY",
        phoneNumber: "+91 98456 04487",
      },
    ],
    link: "https://drive.google.com/file/d/1zLAVgqIPcSvcUNd6GJ-NxI2ISJ6GvQ9X/view?usp=sharing",
  },
  {
    type: "Non Technical",
    name: "VISUAL VIBES",
    day: "1 and 2",
    fee: 200,
    time: "Througout the day",
    venue: "",
    date: "8th and 9th Dec",
    maxlimit: 1,
    mode: "online",
    image: reel,
    prize: "₹3000",
    registrations: [
      "Spot registrations are available.",
      "Registration fee: ₹ 200",
    ],
    teamReq: [
      "Individual Registration.",
      "Participants can use any camera they prefer: professional, GoPro, drone, or smartphone.",
    ],
    desc: "Visual Vibes is a reel-making contest where participants submit short videos created during Aerophilia '23. You don't need to be an expert in video editing or own an expensive camera to make impressive reels with stunning visual effects. Simple techniques and even a basic smartphone can help you create captivating videos.",
    smallDesc: "Role,Camera,Action:Your story,our screen",
    format: {
      "Rules and Regulations :": [
        "The competition will take place over the two days of the Aerophilia 2023 event.",
        "Reels submitted for the competition must be limited to a maximum duration of 30 seconds",
        " All reels must be original creations of the participants. Plagiarism or the use of others' work is strictly prohibited.",
        " Participants must submit the video through email as a Google Drive file. ",
        "Each participant must post the reel it on their Social Media  tagging @aerophilia_2023 and @sahyadri_college and using the #Aerophilia_2023.",
        "The winners will be announced on the ﬁnal day of the event",
        "Each participant will get an option to submit all their photos and videos shot during the event on the ﬁnal day.",
      ],
    },
    rules: [
      "By entering this competition, you grant the organizers the right to use or publish your name, work, and/or likeness without further compensation. ",
      "The organizers are not responsible for any damage to the camera equipment caused during the event.",
      "The contestants are requested to comply with the organizers in this regard, a violation of which will lead to immediate disqualiﬁcation.",
      "These rules are subjected to change.",
    ],
    judgingCriteria: [
      "The winner will be selected on the basis of",
      "1. Creativity",
      "2 .Storytelling",
      "3.Cinematography",
      "4.Originality",
    ],
    contactDetails: [
      {
        name: "HARSHITH K",
        phoneNumber: "+91 96063 28118",
      },

      {
        name: "KAUSHIK",
        phoneNumber: "+91 76765 86643",
      },
    ],
    link: "https://drive.google.com/file/d/1LhGk1jUjpu7X4mc1_ojJxMGKIwLpeJNo/view?usp=sharing",
  },
  {
    type: "Technical",
    name: "BOT SUMO",
    day: "2",

    time: "11 AM",
    venue: "Badminton court (main block)",
    date: "9th Dec",
    maxlimit: 5,
    mode: "online",
    image: sumo,
    prize: "₹10000",
    registrations: [
      "Spot registrations are available.",
      "Every team has to pay a registration fee of ₹500/- in order to register successfully.",
    ],
    teamReq: [
      "All the team members must be full-time students at an accredited University/College/School.",
      "Students from multiple Colleges can form a team.",
      "There are no restrictions on the number of teams from the same Institute.",
      "The team should contain 3-5 members in total.",
      "Each participant may only be a part of one team.",
    ],
    desc: "The competition will involve two limited sized contesting Sumo bots which will compete within a circular arena. The purpose of the competition will be for one robot to eliminate the other by means of pushing it out of the arena within the time limit. ",
    smallDesc: "Make the bot fight for its life",
    format: {
      "BOT SPECIFICATIONS :": [
        "The weight of the robot should not exceed the limit of 5 Kg.",
        "The dimensions of the bot should not exceed the limit: width: 30 cm length: 30 cm height: 30 cm",
        "A pardon of tolerance in the amounts of 10% will be given in the case of the dimensions and weight.",
        " Any discrepancy in the dimensions will lead to the team disqualification.The bot cannot be made using ready to assemble kits ",
        "Bots can be either wired or wireless.",
      ],
      "ROUND RULES": [
        "The opposition Team will be chosen by drawing lots",
        " If odd number of Bots are present then one Bot will directly go to the next round (Only in the PRELIMINARY).",
        "There will be three sessions, PRELIMINARIES, SEMIFINAL and FINAL.",
        "One who wins the toss will choose the side of the arena.",
        "The winner will be the bot left functioning in the arena.",
        "If a bot falls out of the arena after it has pushed its opponent is considered as out. (Note: No other method of attack is allowed other than pushing, if found will be disqualified).",
        "Each round will be of 5mins.",
        "In case that both the bots are unable to eliminate each other over a period of 5 minutes, the bot which has successfully performed more attacks will be considered as the winner of the round",
        "The bot can be controlled by only one person of the team (for next round it can be changed)",
        "The winners of each session will advance onto the next.",
        "The judge's verdict should be considered final and no arguments will be entertained.",
      ],
    },
    rules: [
      "The judge's verdict should be considered final and no arguments will be entertained.",
    ],
    judgingCriteria: [
      "Each Round will be 5 mins.",
      "The team which pushes the opposite team outside the arena will get 1 Point each time.",
      "After a Bot goes out of the arena two bots should again go to the starting point.",
      "After the 5 mins who has, the highest point will go to the next level.",
      "If the round ends with the tie, there will be a tie breaker of 1 mins.",
    ],
    contactDetails: [
      {
        name: "BHVAISH RAI B: ",
        phoneNumber: "+919591002456",
      },
    ],
    link: "https://drive.google.com/file/d/1MHGR1SJYYbgfjNjHAeHlc9A223q9i4KJ/view?usp=drive_link",
  },
  {
    type: "Technical",
    name: "GOAL IN ",
    day: "1",
    fee: 500,
    time: "11 AM",
    venue: "Badminton court (main block)",
    date: "8th Dec",
    maxlimit: 5,
    mode: "online",
    image: goal,
    prize: " 10000/-",

    registrations: [
      "Spot registrations are available.",
      "Every team has to pay a registration fee of ₹500/- in order to register successfully.",
    ],
    teamReq: [
      "All the team members must be full-time students at an accredited University/College/School.",
      "There are no restrictions on the number of teams from the same Institute.",
      "The team can have a maximum of 5 members and a minimum of 3.",
    ],

    desc: "Two teams will put their distinctive bots against each other on a simulated soccer field, trying to score goals while stopping their opponent from doing the same.",
    smallDesc: "The Ultimate soccer showdown",

    format: {
      "BOT SPECIFICATIONS :": [
        "The weight of the bot must not be more than 5 kg.",
        "The bot's measurements must be 30 cm in length and 30 cm in width. There will be a 10% tolerance allowance for both weight and size. ",
        "Any contravention of the above-given specification will lead to disqualification. ",
        " Bots can be wired or wireless.",
        "Wires must be long enough to reach the corners of the arena.",
        "Teams are not allowed to utilize ready-made bots like those made of Lego bricks",
      ],
    },
    rules: [
      "Each game shall have 2 halves, each half lasting for three minutes. ",
      "Pushing the opponent’s bot into the goalpost is allowed.",
      "Until the end of the two parts, the bot can only be controlled by one individual. Changes to the controller are not permitted. ",
      "During the game, one player should grip the wires of the bot. Throughout the whole game, the wires should be flexible.",
      "A 60-second window will be given if the bot becomes immovable so that it may be fixed.",
      "Each minute they don't complete it, they lose 1 point. ",
      "At any time throughout the game, the ball cannot be raised into the air.",
      "The responsible team will lose 2 points if the ball leaves the arena.",
      "No lifting mechanisms are allowed during the match ",
    ],
    judgingCriteria: [
      "The team will receive 3 points for each goal.",
      "Intentional damage to the opponent's bot or the arena will result in a loss of one point. ",
      "The coordinator's and judges' decisions on time, gameplay, and scoring are final.",
      "No arguments will be entertained; all choices made by the judges or volunteers will be taken into consideration.",
    ],
    contactDetails: [
      {
        name: "RANJEET B",
        phoneNumber: "+918050792346",
      },
    ],
    link: "https://drive.google.com/file/d/1_8xFMmcVM18W7fGDjqqt_j56KLcHgqbY/view?usp=drive_link",
  },
  {
    type: "Technical",
    name: "LIFT OFF!",
    day: "1 & 2",
    time: "1.30 PM",
    venue: "FRONT GROUND",
    date: "8th and 9th Dec",
    maxlimit: 5,
    mode: "online",
    image: Lift,
    prize: "₹35000",
    registrations: ["Registration fee: ₹ 1000 per team"],
    teamReq: [
      "Maximum 5 members in a team.",
      "There are no specific requirements for the team or the team members.",
    ],
    desc: "At the Drone Racing Event, students will design, fabricate, and demonstrate the flight capabilities of racing drones that can excel in meeting the specified mission profile. Skilled pilots will navigate their agile drones through intricate obstacle courses, showcasing cutting-edge engineering, precise control, and fierce competition that highlight the pilots' aerial prowess. If you're looking to be the first to pilot your drone in the race, get there early! Winning teams will receive prizes worth ₹30,000 ",
    smallDesc: "Navigate,Accelerate,Dominate-Master the Skies!",
    format: {
      "COMPETITION RULES:": [
        "The competition will have 3 rounds.",
        "First round will be an obstacle course, followed by a drag race. ",
        "In the first round, participants will have two chances to fly their drones, and the best performance will be considered.",
        "Third round is a special round announced during the event.",
        "No participants are allowed inside the arena. ",
        "Trial/practice runs in the arena are not allowed.",
        "All teams are advised to keep a pair of charged batteries.",
      ],
    },
    rules: [
      "Frame size should be between 180 mm to 500 mm",
      "Battery or power supply should not exceed 6s or 24V",
      "Must be operated in Line of sight.",
      "The radio telemetry should be 900MHz to 2.4 GHz.",
      "Ready-made drones are not allowed.",
      "The event organizers reserve the right to stop the match at any point of time if they deem that the match is turning out to be dangerous.",
      "The contestants are requested to comply with the organizers in this regard, violation of which will lead to immediate disqualification. ",
      "Any changes in the rules will be notified to the participants via their registered emails. ",
      "The decision of organizers will be final and binding on all. And the organizers hold all the right to change any or all rules, and conditions declared.",
      "The organizers are not responsible for any damage to the drones caused during the race.",
    ],
    judgingCriteria: [
      "The score will be calculated based on time, number of skill points and number of penalties.",
    ],
    contactDetails: [
      {
        name: "Chirag R.P",
        phoneNumber: "+91 7975660223",
      },
      {
        name: "Shayaan Fayaz ",
        phoneNumber: "+91 8095686687",
      },
    ],
    link: "https://drive.google.com/file/d/1hWZw83mXQHQAlDwF7oR4SzGZW4jwDYWQ/view?usp=sharing",
  },
  {
    type: "Non technical",
    name: "EClash",
    day: "1 & 2",
    time: "Throughout the day",
    venue: "Online",
    date: "4th to 6th Dec",
    maxlimit: 4,
    mode: "online",
    image: eclash,
    prize: "15000",
    registrations: ["Registration fee: ₹ 500 per team"],
    teamReq: [
      "Maximum 4 members in a team.",
      "All the team members must be full-time students at an accredited University/College/School.",
      "Students from multiple Colleges can form a team.",
      "There are no restrictions on the number of teams from the same Institute.",
      "Each participant may only be a part of one team.",
    ],
    desc: "The competition involves virtual battle royale game i.e. Battlegrounds Mobile India(BGMI) where 100 players are dropped onto a map, and they must scavenge for weapons, equipment, and supplies while eliminating other players. The last surviving player or team wins the match.",
    smallDesc: "Unleash the Warrior Within!",
    format: {
      "Competetion Rules": [
        "In order to be eligible to participate in a Tournament as a player, an individual must have reached 16 years of age or older (i.e., the player has lived for at least 16 calendar years) as of the Registration end date.",
        "Ranking Requirement. All players on a Team’s roster must have held a ranking for BATTLEGROUNDS MOBILE INDIA of a level 25 and above Platinum V Tier, at the time of registration ends for any Official Competition.",
        "Players must be Indian Nationals to participate in the Tournament.",
        "Each Team must designate one player as its captain when completing the online registration process (“Team Captain”). The Team Captain will be responsible for all Team communications with Tournament Officials.",
        "Players may participate in Tournaments or Official Competitions only on mobile phones or approved handheld devices. Players may not use peripheral devices of any kind without explicit written approval of Tournament Officials (including tablets, adapters, controllers, Bluetooth keyboards, and mice). Players may not use an emulator to play on a PC or other device that is not a handheld device.",
        "After a player leaves the in-game lobby, his or her avatar must remain fully clothed in the game for the remainder of the match. Clothing exchanges for cosmetic purposes or comic effect are not permitted inside the game.",
      ],
    },
    rules: [
      "The Tournament Organizer may, in its sole judgment, reject or terminate a player’s right to display an advertisement or sponsorship in any of the categories on the Red Flag List on or adjacent to any stream of BATTLEGROUNDS MOBILE INDIA or on any camera-visible apparel worn during any Online Event.",
      "Cheating is prohibited. Any modification of the BATTLEGROUNDS MOBILE INDIA game client by any player, Team or other Team Member is prohibited. The use of any kind of cheating hardware, device or cheat program, or any similar cheating method such as signaling devices, and hand signals, etc., shall be deemed cheating. Downloading any cheat program to the device used for Official Competition match is strictly prohibited. If anyone found intentionally playing with another player on tournament their team will be disqualified directly.",
      "Intentionally using any in-game bug to seek an advantage is exploiting and is prohibited. Exploiting includes acts such as making use of any game function that, in KRAFTON or the Tournament Organizer’s sole judgement, is not functioning as intended and violates the design purpose of BATTLEGROUNDS MOBILE INDIA.",
      "Playing under another player’s account or Gamer Tag, or soliciting or inducing someone else to play a under another player’s account or Gamer Tag, is prohibited.",
      "Teams and Team Members are not permitted to record, stream or broadcast any matches of the Tournament without prior written permission of  Tournament Organizer.",
      "Team Members may not look at any screen or device that is displaying an observer level view of the current game or any other view other than the Team Member’s own player view (i.e. that is or is capable of showing a neutral view of the map, or another player’s view, such as in an offline event a Team Member cannot look at a screen intended for the audience or production teams). No Team Member or any Team staff member may use any backstage spectator machines to interfere with any game or to communicate with anyone involved in any game. ",
      "If any of the illegal activity or harassment is involved then that particular team will be disqualified.",
    ],
    judgingCriteria: [
      "Teams will register for and compete in the in-game qualifier. Players who have registered for the tournament will have to play 3 matches with their registered team members over the given time period. The top 10 of 3 matches will be considered for evaluation and scored accordingly. In case of a tie, certain parameters such as finishes, survival time, accuracy, etc. will be considered.",
      "There will be total of 3 rounds in which only top 15 teams will be put to considerations.",
      "Each kill will add up 1 point to the team and score is evaluated with respect to the table given below.",
      "Ties between two Teams during Official Competitions will be determined in the order of (a) total times of winning the first placement across all the Tournament games; (b) total accumulated placement points across all Tournament Games in the applicable Tournament; (c) total accumulated finishes across all Tournament Games in the applicable Tournament; and (d) placement in the most recent match of the Tournament.",
    ],
    contactDetails: [
      {
        name: "Mahaan Bhat",
        phoneNumber: "+91 8971206807",
      },
    ],
    link: "https://drive.google.com/file/d/1lxno8Hu5ZbDOVhu81k3tYQdRwvkonjWH/view?usp=sharing",
  },
  {
    type: "Non technical",
    name: "FIRE POWER",
    day: "1 & 2",
    time: "Throughout the day",
    venue: "Offline",
    date: "8th and 9th Dec",
    image: firepower,
    maxlimit: 6,
    mode: "online",
    prize: "7000",
    registrations: ["Registration fee: ₹ 500 per team"],
    teamReq: [
      "Each team can have a maximum of 6 members (5 players + 1 substitute)",
      "Each match is a custom game with Overtime Enabled",
    ],
    desc: "A Team-based tactical first-person shooter where two teams, Attackers and Defenders, compete. Attackers aim to plant a bomb at designated sites, while Defenders try to prevent it. Each player selects an Agent with unique abilities to achieve their objective in this competitive and strategic game. Multiple teams will progress forward in a single elimination tournament bracket for their battle to be rewarded with exciting prizes, swags and other benefits.",
    smallDesc: "Unleash the Warrior Within!",
    format: {
      "Competetion Rules": [
        "Team needs to be ready 10 mins prior to their designated time slots and assemble in the venue.",
        "Any kind of Threat Full comments/ Toxic Behavior in the venue may lead to penalty or even disqualification of the team.",
        "If a player is found to be cheating by abusing hacks, the player and his/her Team will be directly disqualified.",
        "A maximum of one Tactical Timeout is given for each team in each Half of the game.",
        
      ],
    },
    rules: [
      "Team members must be full-time students at an accredited University/College/School.",
      "Players should be 16 yrs or older.",
      "Students from multiple colleges can form a team.",
      "There are no restrictions on the number of teams from the same Institute.",
      "Each participant may only be a part of one team.",
      "Each Team must designate one player as its captain when completing the online registration process. The Team Captain will be responsible for all Team communications with Tournament Officials.",
      "Each team member must specify their Player ID before the event day.",
    ],
    judgingCriteria: [
      "The team with the maximum total score from all the rounds will be declared as the winner.Points are assigned with respect to kills and the position acquired.",
      
    ],
    contactDetails: [
      {
        name: "Toshan S Maindan",
        phoneNumber: "+91  9731581062",
      },
    ],
  }
];
